/*******************************************************************************
 * Copyright (c) 2012, Jean-David Gadina <macmade@eosgarden.com>
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @header          NotificationCenter.h
 * @author          Jean-David Gadina <macmade@eosgarden.com>
 * @copyright       (c) 2012, eosgarden
 */

#ifndef EOS_NOTIFICATION_CENTER_H
#define EOS_NOTIFICATION_CENTER_H

#include <list>
#include <map>
#include <string>
#include <memory>
#include "Object.h"
#include "Notification.h"
#include "Observer.h"
#include "Lock.h"

namespace EOS
{
    /*!
     * @class           EOS::NotificationCenter
     * @abstract        ...
     * @description     ...
     */
    class NotificationCenter: public Object
    {
        public:
            
            /*!
             * @method          EOS::NotificationCenter::NotificationCenter
             * @abstract        ...
             * @description     ...
             */
            NotificationCenter();
            
            /*!
             * @method          EOS::NotificationCenter::~NotificationCenter
             * @abstract        ...
             * @description     ...
             */
            ~NotificationCenter();
            
            /*!
             * @method          EOS::NotificationCenter::defaultCenter
             * @abstract        ...
             * @description     ...
             */
            static NotificationCenter & defaultCenter();
            
            /*!
             * @method          EOS::NotificationCenter::addObserver
             * @abstract        ...
             * @description     ...
             */
            void addObserver( const Observer &, const std::string & );
            
            /*!
             * @method          EOS::NotificationCenter::removeObserver
             * @abstract        ...
             * @description     ...
             */
            void removeObserver( const Observer &, const std::string & );
            
            /*!
             * @method          EOS::NotificationCenter::postNotification
             * @abstract        ...
             * @description     ...
             */
            void postNotification( const Notification & );
            
            /*!
             * @method          EOS::NotificationCenter::postNotification
             * @abstract        ...
             * @description     ...
             */
            void postNotification( const std::string & );
            
            /*!
             * @method          EOS::NotificationCenter::postNotification
             * @abstract        ...
             * @description     ...
             */
            void postNotification( const std::string &, const Object & );
            
            /*!
             * @method          EOS::NotificationCenter::postNotification
             * @abstract        ...
             * @description     ...
             */
            void postNotification( const std::string &, const Object &, const Notification::Infos & );
            
        protected:
            
            /*!
             * @typedef         EOS::NotificationCenter::observerList
             * @abstract        ...
             * @description     ...
             */
            typedef std::list< const void * > _observerList;
            
            /*!
             * @typedef         EOS::NotificationCenter::
             * @abstract        ...
             * @description     ...
             */
            typedef std::map< std::string, _observerList > _notificationList;
            
            /*!
             * @var             EOS::NotificationCenter::_lock
             * @abstract        ...
             * @description     ...
             */
            Lock _lock;
            
            /*!
             * @var             EOS::NotificationCenter::_observers
             * @abstract        ...
             * @description     ...
             */
            _notificationList _observers;
    };
}

#endif /* EOS_NOTIFICATION_CENTER_H */
